### PR TITLE
Added: Notebooks/pinecone_demo_transcript_merged_conversation.ipynb

### PR DESCRIPTION
**Pull request by SartajBhuvaji**
Added: Notebooks/pinecone_demo_transcript_merged_conversation.ipynb

- Used @PrachiteeChouhan31 's logic to combine conversations if the speaker is in sequence in the data frame.
- Tested using the same user query.

### CODE REVIEW

**Comment by SartajBhuvaji** [comment]
Added 2 more research papers based on Agents from LangChain

**Review by PrachiteeChouhan31 — COMMENTED** [review]
The scores has reduced when we combine adjacent same speaker.

**Comment by SartajBhuvaji** [comment]
Yes. In an another notebook, let's try different distance metrics and then compare the scores.

**Review by madhuroopa — APPROVED** [review]

**Comment by SartajBhuvaji** [comment]
Changed id's to be sequential and added fetch() to retrieve conversations in the window using ids.

**Review by PrachiteeChouhan31 — APPROVED** [review]
valid

**Pull request merged**
