### PR TITLE
Added initial notebooks : Pinecone DB

### PR DESCRIPTION
**Pull request by SartajBhuvaji**
Added notebooks to play around with Pinecone

1. pinecone_trial_1.ipynb
getting to know pinecone and understanding the basic functions

2. pinecone_demo_transcript.ipynb
implementing data store and querying using a demo transcript

### CODE REVIEW

**Comment by PrachiteeChouhan31** [comment]
The scores are good. but I was thinking can we join adjacent rows with same speaker together and then get embedding.

**Comment by jay-singhvi** [comment]
This could increase the content we send to llm for processing but it also means llm will get more context about the topic

**Comment by SartajBhuvaji** [comment]
@PrachiteeChouhan31 @jay-singhvi 
Yes, that's a great idea! 

Let us decide the context window size and then in v2 we can send out a second query to Pinecone to fetch data in that window. This would help us get the relevant context of the conversation too.

**Comment by madhuroopa** [comment]
@SartajBhuvaji  are you talking about the + secs and - secs content to be retrieved when queried ?

**Comment by SartajBhuvaji** [comment]
@madhuroopa  Yes. +/- window size data/

**Review by PrachiteeChouhan31 — APPROVED** [review]
LGTM.

**Pull request merged**
