### PR TITLE
Pinecone database with delta and returning unique and sorted text

### PR DESCRIPTION
**Pull request by PrachiteeChouhan31**
Added notebook to query pinecone DB for the second time and collect conversations within the delta window.

### CODE REVIEW

**Comment by SartajBhuvaji** [comment]
Changed top_k =1

**Review by SartajBhuvaji — APPROVED** [review]
Approved!

**Review by madhuroopa — APPROVED** [review]

**Review by madhuroopa — APPROVED** [review]

**Comment by SartajBhuvaji** [comment]
Hey @PrachiteeChouhan31 ,

File DS_Store is blocking the pull, can you delete it from your repo, so that we are able to merge the request?

Thanks!

**Comment by SartajBhuvaji** [comment]
Secrets revoked. GitGuarding test passed. Hence merging PR.

**Pull request merged**
