### PR TITLE
Added Pinecone serverless with delta conversations

### PR DESCRIPTION
**Pull request by SartajBhuvaji**
- Added src/db/pinecone_serverless.py

Using Pinecone serverless to upload data, query it along with the delta window
Also added a parser that parses the delta conversations into a data frame.

### CODE REVIEW

**Comment by madhuroopa** [comment]
Hey @SartajBhuvaji,

As we need to store the corresponding video file of a meeting in the firebase, there should be another key value pair in the JSON document for the video file storage.  Can you please add that to the JSON doc structure.

**Review by PrachiteeChouhan31 — COMMENTED** [review]
Can you make a function that will search in entire pinecone database too? that will be helpful when we will use search entire DB button.

**Comment by SartajBhuvaji** [comment]
Hey,

Sure!
- I'll update the JSON to also include a boolean field for each meeting to indicate if the meeting has a video file linked
- I'll add a function to search all namespaces
- And a function to get all the complete transcripts. This should be helpful in case of summarizing the meetings.

**Comment by SartajBhuvaji** [comment]
@madhuroopa 
Fixed  #20 Missing pinecone namespace for the final upstreams

Also, updated the JSON store object. (attached demo JSON store file)
[namespace2.json](https://github.com/SartajBhuvaji/Resonate/files/14076589/namespace2.json)

**Comment by SartajBhuvaji** [comment]
@PrachiteeChouhan31 
Added the query_every_namespace(query) function that queries all namespaces in the index.

**Comment by madhuroopa** [comment]
Hey @SartajBhuvaji,

Can you add small docstrings to each method for quicker understanding.

**Comment by SartajBhuvaji** [comment]
@madhuroopa 

Added comments for important functions.

**Review by PrachiteeChouhan31 — COMMENTED** [review]
when pinecone is returning ids like, 23,24. Then delta is returned redundant ids. Please update query_delta_conversation() to deal with this scenario. Also, it should return sorted dataframe(based on id).

**Review by madhuroopa — APPROVED** [review]
looks good to me

**Review by PrachiteeChouhan31 — APPROVED** [review]
works good!

**Pull request merged**
